name: Pipeline Python

on:
  push:
  pull_request:

jobs:
  teste:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Executar script
        run: python calculadora.py

      - name: Executar teste
        run: python teste.py 